/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "脚手架": {
      "key": "脚手架",
      "scope": "tags",
      "path": "/tag/脚手架/",
      "pageKeys": [
        "v-5ab85aa4"
      ]
    },
    "router": {
      "key": "router",
      "scope": "tags",
      "path": "/tag/router/",
      "pageKeys": [
        "v-53752e80"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-328ffa76"
      ]
    }
  },
  "categories": {
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-5ab85aa4",
        "v-53752e80"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "categories",
      "path": "/categories/工具/",
      "pageKeys": [
        "v-328ffa76"
      ]
    }
  },
  "timeline": {}
}